testdeck/testdeck

.gitignore
index.ts
test.ts
typings.json

should solve #5 and also adds the ability to return promises in hooks on which mocha will wait for either their resolve or reject and will fail if it is rejected. Also (of course) adapted test.ts to reflect the changes made to the source.
And added typings because... it kinda made sense and I couldn't find find a @types-npm-package for symbol-shim (would have been dev-dependency).
Sorry for my (perhaps?) bad english. Greetings from germany.

Added Asynchronous Lifecycle hooks

---

package.json

Without the `typings` property, the typescript compiler (v2.0.3) does not find this module.
Adding this property fixed the problem for me.

Added "typings" property

---

bin/watch.ts

This can be used to submit the 'files' argument to mocha when
testing from a non default location.
(Should fix #15)

Forward all unparsed parameters of watch script to mocha

---

index.d.ts

I started getting a compile error about an implicit any Suite constructor after doing some upgrades so here is the tiny patch that resolves it.

Add explicit "any" return type to Suite constructor

---

bin/watch.ts

The `mocha` executable say :
> This tiny wrapper file checks for known node flags and appends them
when found, before invoking the "real" _mocha(1) executable.
close #48

use directly the binaries and mocha wrapper

---

README.md
index.ts
package.json
test.ts
tests/repo/custom-ui/expected.txt
tests/repo/module-usage/expected.txt
tests/repo/setting-up/expected.txt
tests/ts/abstract.inheritance.suite.expected.txt
tests/ts/abstract.inheritance.suite.ts
tests/ts/context.suite.expected.txt
tests/ts/only.suite.expected.txt
tests/ts/only.v2.suite.expected.txt
tests/ts/pending.suite.expected.txt
tests/ts/pending.v2.suite.expected.txt
tests/ts/retries.suite.expected.txt
tests/ts/suite.inheritance.suite.expected.txt
tests/ts/suite.inheritance.suite.ts
tests/ts/test.suite.expected.txt
tests/ts/test.v2.suite.expected.txt

TODO
~existing failing tests are unrelated and caused by duplicate declarations in the typescript .d.ts files by both ``@types/mocha`` and mocha-typescript. There is an issue and a PR for this, see #61 and #64.~

fix #62: also run tests inherited from [abstract] base classes

---

test.ts

intermediate solution is to run npm pack with the --quiet option
bug report has been filed over at https://github.com/npm/npm/issues/20806

fix #74 failing tests due to change in behaviour of npm pack

---

CHANGELOG.md
README.md
di/typedi.ts
index.d.ts
index.ts
package.json
test.ts
tests/ts/di.typedi.suite.expected.txt
tests/ts/di.typedi.suite.ts
tsconfig.json

This features allows custom DI (Dependency Injection) systems to be registered and used by mocha-typescript.
Supports 'typedi' by requiring `mocha-typescript/di/typedi`.

feat: support for custom DI, support for typedi

---

CHANGELOG.md
package.json

Support for dependency injection was shipped without the promised "mocha-typescript/di/typedi" module, adding the di/typedi.js in the package.

fix: include di/typedi.js in the package

---

CHANGELOG.md
globals.d.ts
index.d.ts

@types/mocha has been refactored and introduced new interfaces for
the 'suite' and 'test' functions. Now the new interfaces will
be augmented by mocha-typescript.

fix: Augment the new @types/mocha interfaces

---

index.d.ts
index.ts
package.json
test/it/fixtures/abstract.inheritance.override1.suite.expected.txt
test/it/fixtures/context.suite.ts
tslint.json

The mocha-typescrip use deprecated @types/mocha APIs.
It will use the more recent APIs now, it may require you to update @types/mocha.

fix: Use new @types/mocha APIs and fix tslint deprecation erros

---

index.ts
package.json
test/it/AsyncSuiteIT.ts
test/it/ContextSuiteIT.ts
test/it/CustomUiPackageIT.ts
test/it/DependencyInjectionSuiteIT.ts
test/it/InheritanceSuiteIT.ts
test/it/ModuleUsagePackageIT.ts
test/it/OnlySuiteIT.ts
test/it/ParamsSuiteIT.ts
test/it/PendingSuiteIT.ts
test/it/RetriesSuiteIT.ts
test/it/SettingUpPackageIT.ts
test/it/SkipSuiteIT.ts
test/it/StandardFeaturesSuiteIT.ts
test/it/fixtures/packages/custom-ui/package.json
test/it/fixtures/packages/custom-ui/test/test.ts
test/it/fixtures/packages/setting-up/test/tests.ts
test/it/util.ts

This removes all suite.on() declarations as they are redundant and will also lead to malfunctioning suites when using the declarative API.
However, this will require users of the OOP api to explicitly import timeout, slow and so on.
But I am fine with that.
@pana-cc What do you think?

fix #120: get rid of redundant declarations in the custom ui

---

README.md
docs/index.md

- also fix links in docs/index.md
@pana-cc you will need to regenerate the documentation site, please check the links prior to publishing it, thanks.

fix #128: make documentation links point to master

---

index.d.ts

Params is a helpful, well tested feature of this library. This change allows it to be imported alongside test and suite for use in user-land projects. With this change, `import { params, suite, test } from 'mocha-typescript';` is now possible, where previously this would have required a @ts-ignore

fix: expose params constant from exported typings

---

index.ts
test/it/fixtures/params.async.suite.expected.txt
test/it/fixtures/params.naming.suite.expected.txt
test/it/fixtures/params.only.suite.expected.txt
test/it/fixtures/params.skip.suite.expected.txt
test/it/fixtures/params.suite.expected.txt

*WIP*
@pana-cc I need your feedback here.
What this does is declare a subsuite using describe(). The parameterised tests will then be applied/created during runtime and not forefront. The reason for this is that with large numbers of testcases loaded from JSON or CSV, the startup performance of the system would be quite low.
I have adjusted the expected results for the ParamsSuite so far and the output is of course a little bit different than it was before (with the subsuites). All of the other expected results need to be adjusted, too.
Before I do this, though, as it is a lot of work, what do you think of it?

feature(#145): run parameterised tests lazily

---

bin/watch
globals.d.ts
index.d.ts
index.ts
package.json
test/it/AbstractPackageITBase.ts
test/it/SkipSuiteIT.ts
test/it/WatcherPackageIT.ts
test/it/fixtures/packages/custom-ui/package.json
test/it/fixtures/packages/custom-ui/test/test.ts
test/it/fixtures/packages/watcher/expected.txt
test/it/fixtures/packages/watcher/package.json
test/it/fixtures/packages/watcher/test/mocha.opts
test/it/fixtures/packages/watcher/test/tests.ts
test/it/fixtures/packages/watcher/tsconfig.json
test/it/fixtures/skip.suite.expected.txt
test/it/fixtures/skip.suite.ts

Not ready for PR yet, but I want to check what will happen with the build machines.

Adding a watcher test

---

docs/api.md
globals.d.ts
index.d.ts
index.ts

This improves on the available docs/api.md API documentation.
- reexport pending on both suite and test
What is missing is documentation on custom traits. But since this is a rather fringe usecase, I think that we can go without it for now, especially since these cannot be used with parametrised tests...

fix #126: improve api documentation

---

lerna.json
packages/@testdeck/core/index.ts
packages/@testdeck/core/test.ts

- temporarily disabling the di-typedi package as there are unrelated errors

fix #248: getters and setters will cause error when initializing the suite

---

packages/@testdeck/mocha/bin/watch

This is an issue for lerna projects, forcing the path of the binary is not the correct behavior, the .bin is at the project level and not the package level.
Npm has already a way to pick the correct binary we should keep this behavior by default.
Example :
```
➜  test_bin cat package.json|grep test
"name": "test_bin",
"test": "tsc --version"
➜  test_bin npm run test    
> test_bin@1.0.0 test /home/david/Code/tests/test_bin
> tsc --version
Version 3.7.2
➜  test_bin rm -Rf node_modules 
➜  test_bin npm run test       
> test_bin@1.0.0 test /home/david/Code/tests/test_bin
> tsc --version
message TS6029: Version 1.5.3
```

let npm resolve mocka and tsc binary

---

packages/core/index.ts
packages/core/test.ts
packages/jasmine/index.ts
packages/jest/index.ts

fix #265: support running afterAll/afterEach hooks in reverse order

fix #265: support running afterAll/afterEach hooks in reverse order

---

packages/core/package.json
packages/jasmine/package.json
packages/jest/package.json
packages/mocha/package.json

fix #267: add missing keywords to package manifest

fix #267: add missing keywords to package manifest

---

packages/core/index.ts

fix gh-254: use Object.getOwnPropertyDescriptor instead of accessing the fields directly.

fix gh-254: use Object.getOwnPropertyDescriptor instead of accessing the fields directly

---

packages/core/index.ts
packages/core/package.json
packages/core/test.ts
packages/jest/index.ts
packages/mocha/index.d.ts
packages/mocha/index.ts
packages/mocha/test.ts

Don't merge yet!
There are tests added to the core, and the `this` seems to be passed down to test methods properly.
I have to just add typing's for mocha/jest/etc. and eventually add a test or two there as well.

Add a 'context' symbol and expose mocha context

---

.github/workflows/main.yml
packages/mocha/bin/watch

Passes new `--options` flag to mocha
Fixes #289

Use new mocha options flag and config

---

.github/workflows/main.yml

[INTERNAL] add SonarCloud to check for code coverage and other quality reports
