testdeck/testdeck

- README.md
- bin/watch.ts
- index.ts
- package.json
- tsconfig.json
Should be properly added to package.json's bin scripts and tested on mac.
> Add a script file that will run tsc -w and mocha

- README.md
Makes reading through it a little prettier.
> Added more syntax highlighting to README.md

- README.md
> chore (Readme.md): Generated test example syntax

- globals.d.ts
- index.d.ts
- index.ts
- package.json
> Add @types/mocha as dependency

- README.md
- index.ts
- package.json
- test.ts
- tests/ts/abstract.inheritance.override1.suite.expected.txt
- tests/ts/abstract.inheritance.override1.suite.ts
- tests/ts/abstract.inheritance.override2.suite.expected.txt
- tests/ts/abstract.inheritance.override2.suite.ts
- tests/ts/suite.inheritance.override1.suite.expected.txt
- tests/ts/suite.inheritance.override1.suite.ts
- tests/ts/suite.inheritance.override2.suite.expected.txt
- tests/ts/suite.inheritance.override2.suite.ts
> fix #71 add support for test method override

- index.d.ts
- package.json
- test.ts
reactivate PackageTest suite
bump dependency towards mocha to ^5.2.0
bump dependency towards @types/mocha to ^5.2.0
> fix #80 add missing augmentations to Test and Suite

- README.md
- docs/api.md
- docs/di.md
- docs/extendbehave.md
- docs/ide.md
- docs/oop.md
- docs/setup.md
- docs/usage.md
- docs/watcher.md
- package.json
- test/it/fixtures/context.suite.ts
**WORK IN PROGRESS**
@pana-cc I'd like to have your opinion on the current refactoring.
see https://github.com/pana-cc/mocha-typescript/tree/gh-115 for the refactored documentation.
**TODO**
**NOTES**
- the absolute links are necessary since we want this to work on npmjs.com
- currently, these links point to the feature branch and will be updated to point to master as soon as this gets approved
> chore #115: refactor documentation

- test/it/constants.ts
- test/it/fixtures/context.suite.ts
- test/it/fixtures/di.typedi.suite.ts
- test/it/fixtures/only.suite.ts
- test/it/fixtures/only.test.suite.ts
- test/it/fixtures/only.v2.suite.ts
- test/it/fixtures/packages/custom-ui/expected.txt
- test/it/fixtures/packages/custom-ui/test/test.ts
- test/it/fixtures/packages/module-usage/expected.txt
- test/it/fixtures/packages/module-usage/test/tests.ts
- test/it/fixtures/pending.suite.ts
- test/it/fixtures/pending.v2.suite.ts
- test/it/fixtures/test.suite.expected.txt
- test/it/fixtures/test.suite.ts
- test/it/fixtures/test.v2.suite.expected.txt
- test/it/fixtures/test.v2.suite.ts
> fix #134: compensate for appveyor running slower than other VMs

- README.md
- docs/index.md
- docs/oop_params.md
- docs/usage.md
- test/it/ParamsSuiteIT.ts
- test/it/fixtures/params.async.suite.expected.txt
- test/it/fixtures/params.async.suite.ts
also add required async tests for parameterised test methods
> improve documentation on parameterised tests

- README.md
- docs/index.md
- docs/oop_generated.md
- test/it/GeneratedSuiteIT.ts
- test/it/fixtures/generated.suite.expected.txt
- test/it/fixtures/generated.suite.ts
chore(#148): improve documentation on generated test suites
chore(#148): add required test suite
> improve documentation on generated test suites

- bin/watch
- docs/watcher.md
- package.json
- test/it/AbstractPackageITBase.ts
- test/it/ModuleUsagePackageIT.ts
- test/it/SettingUpPackageIT.ts
- test/it/WatcherPackageIT.ts
- test/it/fixtures/packages/watcher/package.json
- test/it/util.ts
I think that all that had to be done was done 🥇
> fix #165: add option to watcher to limit the times that it is being run

- package.json
- packages/@testdeck/core/index.ts
- packages/@testdeck/core/test.ts
- packages/@testdeck/jasmine/test.ts
- packages/@testdeck/jest/jest.config.js
- packages/@testdeck/jest/package.json
- packages/@testdeck/jest/test.ts
- packages/@testdeck/mocha/test.ts
fixes issues: #189, #191, #193
> fix #193: adjust jest configuration

- package.json
- packages/@testdeck/core/package.json
- packages/@testdeck/di-typedi/package.json
- packages/@testdeck/jasmine/package.json
- packages/@testdeck/jest/package.json
- packages/@testdeck/mocha/package.json
> chore #224: fix package.json links and descriptions

- .travis.yml
- appveyor.yml
> chore(CI): build only latest non-lts and currently supported lts version

- README.md
fix #270: packages have been moved
> fix #270: packages have been moved

- packages/core/index.ts
> fix #333: fix compatibility with typescript 4.8 and strictNullChecks

- .github/workflows/main.yml
> Revert "enable CI on all branches"

- .github/workflows/main.yml
- .gitignore
- package-lock.json
- packages/vitest/LICENSE
- packages/vitest/README.md
- packages/vitest/index.d.ts
- packages/vitest/index.ts
- packages/vitest/package.json
- packages/vitest/test.ts
- packages/vitest/tsconfig.json
- packages/vitest/tslint.json
- packages/vitest/vitest.config.ts
> add vitest support

- packages/di-typedi/package.json
> @testdeck/di-typedi does not depend on @testdeck/core

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/documentation.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/ISSUE_TEMPLATE/internal.md
- .github/ISSUE_TEMPLATE/question.md
- .github/ISSUE_TEMPLATE/release.md
> [INTERNAL] Add additional issue templates

- package.json
- packages/core/package.json
- packages/di-typedi/package.json
- packages/di-typedi/test.ts
- packages/jasmine/package.json
- packages/jest/package.json
- packages/mocha/package.json
- packages/vitest/package.json
> [INTERNAL] Push down dependencies into requiring packages so that errors show up early

- packages/core/.mocharc.json
- packages/core/.nycrc
- packages/core/package.json
- packages/di-typedi/.mocharc.json
- packages/di-typedi/.nycrc
- packages/di-typedi/package.json
- packages/jasmine/.nycrc
- packages/jasmine/jasmine.json
- packages/jasmine/package.json
- packages/jasmine/test.ts
- packages/jest/jest.config.js
- packages/jest/package.json
- packages/mocha/.mocharc.json
- packages/mocha/.nycrc
- packages/mocha/package.json
- packages/vitest/package.json
- packages/vitest/vitest.config.ts
> [INTERNAL] Reenable coverage checks and coverage reports for all packages

- packages/di-typedi/package.json
- packages/mocha/package.json
> [INTERNAL] Remove nyc configuration from all package.json

- .npmrc
> Disable package-lock.json on root package

- .github/workflows/main.yml
> [INTERNAL] Update Github Workflow

- package.json
- packages/core/package.json
- packages/di-typedi/package.json
- packages/jasmine/package.json
- packages/jest/package.json
- packages/mocha/package.json
- packages/vitest/package.json
> Reconfigure Package Scripts

- .github/workflows/main.yml
- packages/vitest/package.json
- packages/vitest/vitest.config.ts
> [INTERNAL] Enable coverage reports for @testdeck/vitest

- .github/workflows/main.yml
> [INTERNAL] Include tests in sonar report

- README.md
- packages/core/README.md
- packages/di-typedi/README.md
- packages/jasmine/README.md
- packages/jest/README.md
- packages/mocha/README.md
- packages/vitest/README.md
> Streamline Badges in Package Readmes

- packages/jasmine/test.ts
- packages/jest/test.ts
- packages/mocha/test.ts
- packages/vitest/test.ts
> Fix Randomly Failing Test Timeouts

- packages/core/README.md
- packages/di-typedi/README.md
- packages/jasmine/README.md
- packages/jest/README.md
- packages/mocha/README.md
- packages/vitest/README.md
> [DOCUMENTATION] Add QA Badges to Package Readmes

- packages/core/index.ts
- packages/core/test.ts
> [FEATURE] Notify Users of Deprecated API 

- packages/core/index.ts
- packages/core/test.ts
Reverts testdeck/testdeck#374
Needs more extensive testing.
> Revert "[FEATURE] Notify Users of Deprecated API "

- README.md
- packages/core/README.md
- packages/di-typedi/README.md
- packages/jasmine/README.md
- packages/jest/README.md
- packages/mocha/README.md
- packages/vitest/README.md
> [DOCUMENTATION] Streamline READMEs of Individual Packages
